smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem

quarkus.smallrye-openapi.security-scheme-name=bearer_auth
quarkus.smallrye-openapi.security-scheme-description=Use /users/login to obtain token and include it in the Authorization
quarkus.smallrye-openapi.store-schema-directory=${project.build.directory}/swagger/
quarkus.smallrye-openapi.open-api-version=3.0.3
