# JWT configuration
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=notes-app

# OpenAPI configuration
quarkus.smallrye-openapi.security-scheme-name=bearer_auth
quarkus.smallrye-openapi.security-scheme-description=Use /users/login to obtain token and include it in the Authorization
quarkus.smallrye-openapi.store-schema-directory=${project.build.directory}/swagger/
quarkus.smallrye-openapi.open-api-version=3.0.3

# CORS configuration
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.access-control-allow-credentials=true
quarkus.http.cors.exposed-headers=Location,Content-Disposition

# Database configuration
%sql.persistence=sql
%sql.quarkus.datasource.db-kind=postgresql
%sql.quarkus.datasource.username=notes
%sql.quarkus.datasource.password=notes
%sql.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/notes
%sql.quarkus.hibernate-orm.database.generation=update
%sql.quarkus.hibernate-orm.schema-management.strategy=update
