@startuml
skinparam rectangle {
  BorderColor Black
  FontSize 14
}

skinparam backgroundColor transparent

skinparam arrow {
  Color Grey
  Thickness 1
}

top to bottom direction

rectangle "Domain Layer\n(Entities, Validators, Services)" as DomainLayer
rectangle "Persistence\n(Repositories)" as Persistence
rectangle "Controller\n(Controllers, Mappers)" as Controller
rectangle "Presentation\n(Presenters, Resources)" as Presentation

Presentation --> Controller
Controller --> DomainLayer
Persistence -up-> DomainLayer

@enduml
